const STORAGE_KEY='morning-device-self-check-records';
const THEME_KEY='morning-device-self-check-theme';
const COMMENTS=['今日设备运行正常。','系统状态优秀。','建议继续保持良好作息。','已超过99%的虚构用户。','数据已同步至不存在的国家晨勃数据库。','检测到稳定输出，建议颁发小红花。','系统自检结束，未发现离谱波动。'];
const STATUS={idle:{label:'无事发生',emoji:'😴',desc:'设备低功耗待机，一切波澜不惊。',color:'#94a3b8'},normal:{label:'正常升旗',emoji:'🌅',desc:'系统按标准流程稳定启动。',color:'#f59e0b'},amazing:{label:'状态惊人',emoji:'🚀',desc:'今日性能曲线过于优雅，疑似超频。',color:'#10b981'},refuse:{label:'拒绝回答',emoji:'🙈',desc:'系统拒绝提供更多遥测信息。',color:'#f43f5e'}};
const app=document.getElementById('app');
let state={tab:'home',records:loadRecords(),theme:loadTheme(),toast:''};
applyTheme();render();
function todayKey(){return new Date().toISOString().slice(0,10)}
function fmtDate(k){return new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(`${k}T00:00:00`))}
function monthKey(k){return k.slice(0,7)}
function monthDates(key=todayKey()){const [y,m]=key.split('-').map(Number);const total=new Date(y,m,0).getDate();return Array.from({length:total},(_,i)=>`${key.slice(0,7)}-${String(i+1).padStart(2,'0')}`)}
function loadRecords(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]').sort((a,b)=>a.date.localeCompare(b.date))}catch{return[]}}
function saveRecords(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.records))}
function loadTheme(){return localStorage.getItem(THEME_KEY)==='dark'?'dark':'light'}
function applyTheme(){document.documentElement.classList.toggle('dark',state.theme==='dark');localStorage.setItem(THEME_KEY,state.theme)}
function todayRecord(){return state.records.find(r=>r.date===todayKey())}
function upsert(status){const now=new Date().toISOString();const current=todayRecord();state.records=[...state.records.filter(r=>r.date!==todayKey()),{date:todayKey(),status,createdAt:current?.createdAt||now,updatedAt:now}].sort((a,b)=>a.date.localeCompare(b.date));saveRecords();toast(COMMENTS[Math.floor(Math.random()*COMMENTS.length)]);render()}
function streaks(){const sorted=[...state.records].sort((a,b)=>a.date.localeCompare(b.date));let longest=0,run=0,prev='';for(const r of sorted){if(!prev){run=1}else{const delta=(new Date(`${r.date}T00:00:00`)-new Date(`${prev}T00:00:00`))/86400000;run=delta===1?run+1:1}longest=Math.max(longest,run);prev=r.date}let current=0;const set=new Set(sorted.map(r=>r.date));const d=new Date(`${todayKey()}T00:00:00`);while(set.has(d.toISOString().slice(0,10))){current++;d.setDate(d.getDate()-1)}return{current,longest}}
function stats(){const m=monthKey(todayKey());const month=state.records.filter(r=>monthKey(r.date)===m);const good=month.filter(r=>r.status==='normal'||r.status==='amazing').length;const counts={idle:0,normal:0,amazing:0,refuse:0};state.records.forEach(r=>counts[r.status]++);return{...streaks(),monthCount:month.length,goodRate:month.length?Math.round(good/month.length*100):0,counts}}
function achievements(){const s=stats();const dates=monthDates().filter(d=>d<=todayKey());const set=new Set(state.records.map(r=>r.date));let amazingRun=0,amazingBest=0;const a=state.records.filter(r=>r.status==='amazing').sort((x,y)=>x.date.localeCompare(y.date));for(let i=0;i<a.length;i++){if(i===0) amazingRun=1; else amazingRun=((new Date(`${a[i].date}T00:00:00`)-new Date(`${a[i-1].date}T00:00:00`))/86400000===1)?amazingRun+1:1; amazingBest=Math.max(amazingBest,amazingRun)}return[{title:'初次记录',desc:'完成第一次设备自检。',ok:state.records.length>=1},{title:'连续7天',desc:'连续记录 7 天，没有偷懒。',ok:s.longest>=7},{title:'连续30天',desc:'连续记录 30 天，系统稳定得离谱。',ok:s.longest>=30},{title:'状态惊人连续3天',desc:'连续 3 天保持火箭级输出。',ok:amazingBest>=3},{title:'本月全勤',desc:'本月到今天为止每天都有记录。',ok:dates.every(d=>set.has(d))}]}
function exportJson(){const blob=new Blob([JSON.stringify(state.records,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`晨间设备自检-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{state.records=JSON.parse(String(reader.result)||'[]').sort((a,b)=>a.date.localeCompare(b.date));saveRecords();toast('导入完成，历史遥测已经接管。');render()}catch{toast('导入失败，JSON 格式不正确。')}};reader.readAsText(file)}
function clearAll(){if(confirm('确认清空全部记录吗？这个操作无法撤销。')){state.records=[];saveRecords();toast('全部记录已清空。');render()}}
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast='';render()},2600)}
function setTab(tab){state.tab=tab;render()}
function toggleTheme(){state.theme=state.theme==='light'?'dark':'light';applyTheme();render()}
function renderHome(){const current=todayRecord();return `<section class="card"><div class="row"><div><h2>今日状态</h2><div class="muted">每天仅保留一条记录，但可以随时修改今天的结果。</div></div><div class="pill">${current?'已记录':'待记录'}</div></div><div class="status-grid">${Object.entries(STATUS).map(([key,v])=>`<button class="status-btn ${current?.status===key?'active':''}" data-status="${key}"><div class="emoji">${v.emoji}</div><div class="status-title">${v.label}</div><div class="status-desc">${v.desc}</div></button>`).join('')}</div></section>${current?`<section class="card"><div class="muted">今日已保存</div><div style="font-size:28px;font-weight:800;margin-top:8px">${STATUS[current.status].emoji} ${STATUS[current.status].label}</div><div class="muted" style="margin-top:8px">上次更新时间：${new Date(current.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</div></section>`:''}`}
function renderStats(){const s=stats();const recMap=new Map(state.records.map(r=>[r.date,r]));return `<section class="card"><h2>统计面板</h2><div class="stats"><div class="stat"><div class="muted">当前连续</div><div class="v">${s.current} 天</div></div><div class="stat"><div class="muted">最长连续</div><div class="v">${s.longest} 天</div></div><div class="stat"><div class="muted">本月记录</div><div class="v">${s.monthCount} 次</div></div><div class="stat"><div class="muted">优良率</div><div class="v">${s.goodRate}%</div></div></div></section><section class="card"><h2>本月热力图</h2><div class="muted">按天查看状态分布。</div><div class="heatmap">${monthDates().map(d=>{const r=recMap.get(d);const bg=r?STATUS[r.status].color:'#f8e7da';return `<div class="day" title="${d} ${r?STATUS[r.status].label:'未记录'}" style="background:${bg}">${d.slice(-2)}</div>`}).join('')}</div></section><section class="card"><h2>状态占比</h2><div class="pie">${Object.entries(s.counts).map(([k,v])=>`<div class="pie-row"><div><span class="dot" style="background:${STATUS[k].color}"></span>${STATUS[k].emoji} ${STATUS[k].label}</div><strong>${v}</strong></div>`).join('')}</div></section>`}
function renderAchievements(){return `<section class="card"><h2>成就系统</h2><div class="muted">持续记录会自动解锁一些没什么必要但很有趣的徽章。</div><div class="list" style="margin-top:14px">${achievements().map(a=>`<div class="badge ${a.ok?'':'locked'}"><div><div style="font-weight:700">${a.title}</div><div class="muted" style="margin-top:4px">${a.desc}</div></div><div style="font-size:24px">${a.ok?'🏅':'🔒'}</div></div>`).join('')}</div></section>`}
function renderSettings(){return `<section class="card"><h2>设置</h2><div class="actions" style="margin-top:14px"><button class="action" id="export-btn">导出 JSON</button><label class="action">导入 JSON<input class="hidden" id="import-input" type="file" accept="application/json"></label><button class="action" id="clear-btn">清空所有数据</button><button class="action" id="theme-btn">切换深色模式</button></div></section>`}
function render(){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Morning System Check</div><div class="row"><div><h1>晨间设备自检</h1><div class="muted">${fmtDate(todayKey())}</div></div><button class="header-btn" id="theme-toggle">${state.theme==='light'?'🌙 夜间':'☀️ 日间'}</button></div></header>${state.tab==='home'?renderHome():''}${state.tab==='stats'?renderStats():''}${state.tab==='achievements'?renderAchievements():''}${state.tab==='settings'?renderSettings():''}<nav class="tabbar"><div class="tabs">${[{k:'home',e:'☀️',l:'今日'},{k:'stats',e:'📊',l:'统计'},{k:'achievements',e:'🏅',l:'成就'},{k:'settings',e:'⚙️',l:'设置'}].map(t=>`<button class="tab ${state.tab===t.k?'active':''}" data-tab="${t.k}">${t.e}<div>${t.l}</div></button>`).join('')}</div></nav>${state.toast?`<div class="toast">${state.toast}</div>`:''}</div>`;bind()}
function bind(){document.getElementById('theme-toggle')?.addEventListener('click',toggleTheme);document.querySelectorAll('[data-status]').forEach(el=>el.addEventListener('click',()=>upsert(el.getAttribute('data-status'))));document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>setTab(el.getAttribute('data-tab'))));document.getElementById('export-btn')?.addEventListener('click',exportJson);document.getElementById('clear-btn')?.addEventListener('click',clearAll);document.getElementById('theme-btn')?.addEventListener('click',toggleTheme);document.getElementById('import-input')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)importJson(file)})}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'))}
